name: Build

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    name: continuous-integration/github
    permissions:
      contents: read
      packages: write
    steps:
      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version:
            8.0
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 10.x
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: get version
        run: |
          dotnet tool restore
          version=$(dotnet minver)
          echo "REACT_APP_CLIENT_VERSION=${version}" >> "GITHUB_ENV"          
      - name: build
        run: |
          yarn --frozen-lockfile && \
            yarn build:dist && \
            yarn cache clean
      - name: setup node publish
        if: github.event_name == 'push'
        uses: actions/setup-node@v4
        with:
          node-version: 10.x
          registry-url: 'https://npm.pkg.github.com'
      - name: publish
        if: github.event_name == 'push'
        run: |
          yarn version --no-git-tag-version --new-version $(dotnet minver)
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
